# -*- coding: utf-8 -*-
"""Exploratory data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy9I11tihHd6fDrJDLuRVXYRxQd6gLaE
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Step 1: Request the webpage
url = "http://books.toscrape.com/"
response = requests.get(url)

# Step 2: Parse HTML content
soup = BeautifulSoup(response.text, 'html.parser')

# Step 3: Find book listings
books = soup.find_all('article', class_='product_pod')

# Step 4: Extract title and price
data = []
for book in books:
    title = book.h3.a['title']
    price = book.find('p', class_='price_color').text
    data.append({'Title': title, 'Price': price})

# Step 5: Convert to DataFrame and save to CSV
df = pd.DataFrame(data)
df.to_csv('books.csv', index=False)

print("✅ books.csv created successfully.")
print(df.head())  # Preview first 5 rows

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('books.csv')

# Preview data
print("First 5 rows:")
print(df.head())

# Check data types and info
print("\nData Info:")
print(df.info())

# Clean price: remove '£' and convert to float
# If you want to be extra safe, replace both 'Â' and '£' characters
df['Price'] = df['Price'].str.replace('Â', '', regex=False).str.replace('£', '', regex=False).astype(float)

# Summary statistics
print("\nSummary Statistics for Price:")
print(df['Price'].describe())

# Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# Visualize price distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['Price'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Book Prices')
plt.xlabel('Price (£)')
plt.ylabel('Count')
plt.show()

# Detect outliers with boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['Price'], color='orange')
plt.title('Box Plot of Book Prices')
plt.xlabel('Price (£)')
plt.show()

